# Basic
title: XJL's Blog
subtitle: 坚持就是积累。
#welcome_message: <a href="https://github.com/XXXXJL/xxxxjl.github.io" target="_blank">使用这个主题</a>
description: 正在坚持码码ing...
creator: <a href="https://xxxxjl.github.io">@xxxxjl</a>

url: "https://xxxxjl.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问我的Blog

# Navigation buttons in the front page.
#nav:
    #- {title: Projects, description: My Projects, url: 'https://xxxxjl.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: XXXXJL
    # duoshuo: 
    
# Social
social:
    weibo: 
    github: 
    twitter: 
    gplus: 
    mail: duan071361@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
